Product_Wizard_Solution/Product_Wizard/Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Wizard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.Product_Details = new HashSet<Product_Details>();
        }
    
        public int Id { get; set; }
        public int size { get; set; }
        public string Name { get; set; }
        public string link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Details> Product_Details { get; set; }
    }
}

Product_Wizard_Solution/Product_Wizard/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Product_Wizard.Models;

namespace Product_Wizard.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            string extension = System.IO.Path.GetExtension(file.FileName);
            //string name = System.IO.Path.GetFileNameWithoutExtension(file.FileName);
            int size = file.ContentLength;
            if (file != null && size > 0) { 
                if (extension == ".pdf" || extension == ".txt" || extension == ".docx" || extension == ".png" )
                {
                    try
                    {
                        string path = Path.Combine(
                            Server.MapPath(System.Web.Configuration.WebConfigurationManager.AppSettings.Get("UploadFilePath")), 
                            Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        ViewBag.Message = "File uploaded successfully";



                        ProductWizardEntities db = new ProductWizardEntities();
                        Image obj = new Image();
                        obj.Name = file.FileName;
                        obj.size = size;
                        obj.link = path;

                        db.Images.Add(obj);
                        db.SaveChanges();

                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    ViewBag.Message = "Please select pdf,txt,docx file only.";
                }
            }

            else
            {
                ViewBag.Message = "You have not specified a file.";
            }
            return View();
        }
        public ViewResult Downloadpage()
        {
            ProductWizardEntities db = new ProductWizardEntities();
            return View("Downloadpage", from Image in db.Images.Take(10) select Image);
        }
        public ActionResult Download(int id)
        {
            //int id = 5;
            string link = System.Web.Configuration.WebConfigurationManager.AppSettings.Get("UploadFilePath");
            ProductWizardEntities db = new ProductWizardEntities();

            //Image obj = new Image();
             String filename = db.Images.Where(p=> p.Id ==id).Select(p2=>p2.Name).FirstOrDefault();
            //string url = System.Web.Configuration.WebConfigurationManager.AppSettings.Get("UploadFilePath") + filename;
            //return View("Download", url);
            string extension = Path.GetExtension(filename).Replace(".","");
            string FileType = "application/" + extension;
            string fullLink = link + filename;
            return  File(Server.MapPath(fullLink),FileType,filename);
        }
    }
}

Product_Wizard_Solution/Product_Wizard/Views/Image/Downloadpage.cshtml
@model IEnumerable<Product_Wizard.Models.Image>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Download</title>


    @Styles.Render("~/COntent/table.css"),
    @Styles.Render("~/COntent/icon.css")
</head>
<body>
    <div>


        <table class="w3-table w3-striped w3-border" style="width:100%;">
            <tr class="w3-red">
                <th>Sr.No</th>
                <th>Name</th>
                <th>Size</th>
                <th>Link</th>
                <th> Download</th>

                @{ int count = 1;}
            </tr>
            @foreach (var item in Model)
            {


                <tr>
                    @*<td  ><a href='@string.Format("/Employee/update?id={0}", item.ID)'>@item.ID</a></td>*@
                    <td style="text-align:center">@count @*@item.Product_Id*@ </td>
                    <td>@item.Name</td>
                    <td style="text-align:center">@item.size</td>
                    <td style="text-align:center">@item.link</td>
                    <td style="text-align:center"><a href='@string.Format("/Image/Download?id={0}", item.Id)' onclick="return ('Downloading')"><span style="color:red; ">Download</span></td>

                    @{ count = count + 1; }
                </tr>
                        }
        </table>






        @*@Html.ActionLink("Download File", "Download", "Image", new { id = Model.id })*@


        @*@foreach (var item in Model)
        {
            <table>
                <tr>
                    <td>
                        @if (item.Name != null)
                        {
                            @Html.ActionLink("Download", "Image", new { id = item.Id })
                        }
                    </td>

                </tr>
            </table>*@
        }
    </div>
</body>
</html>

Product_Wizard_Solution/Product_Wizard/Views/Image/Index.cshtml
@model Product_Wizard.Models.Image
@{
    Layout = null;
}

<!DOCTYPE html>
@{
    ViewBag.Title = "file";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    

    <h2>Upload file</h2>
    @using (Html.BeginForm("Upload", "Image", FormMethod.Post,
                                 new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="file" id="file" /><br><br>
        <input type="submit" value="Upload file" />
        <br><br>
        @ViewBag.Message
    }
    
    </div>
</body>
</html>

Product_Wizard_Solution/Product_Wizard/Views/Image/Upload.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
</head>
<body>
    <div> done

    <br />
        @ViewBag.Message
    </div>
</body>
</html>